# Jekyll configuration file

# Site settings
title: "My Awesome Site"
email: "your-email@example.com"
description: "A lovely site built with Jekyll and a nice theme."
baseurl: "" # the subpath of your site, e.g. /blog (leave empty for root)
url: "https://pgsch.github.io/coursera-test/" # the base hostname & protocol for your site

# Theme and plugins
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude these files and folders from your site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for your posts and pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Minimal Mistakes theme specific configuration
minimal_mistakes:
  skin: "default"   # Choose your skin: default, dark, or other custom options
  typography:
    enable: true    # Enable improved font rendering